services:
  app:
    image: meals
    build:
      context: .
    ports:
      - "8005:8000"
    environment:
      MEALS_PORT: "8000"
      MEALS_DSN: "root@tcp(db-dev)/meals?parseTime=true"
    depends_on:
      - db-dev
  db-dev:
    image: mysql
    restart: always
    ports:
      - "8001:3306"
    environment:
      MYSQL_DATABASE: meals
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - db_dev_data:/var/lib/mysql
  db-testing:
    image: mysql
    restart: always
    ports:
      - "8002:3306"
    environment:
      MYSQL_DATABASE: meals
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
volumes:
  db_dev_data:
