CREATE TABLE users (
	id INTEGER PRIMARY KEY,
	email TEXT NOT NULL,
	name TEXT NOT NULL,
        password TEXT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
