CREATE TABLE meals (
	id INTEGER PRIMARY KEY,
	user_id INTEGER,
	name TEXT NOT NULL,
	notes TEXT NULL,
	quick BIT DEFAULT 0 NOT NULL,
	family BIT DEFAULT 0 NOT NULL,
	easy BIT DEFAULT 0 NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
