CREATE TABLE users (
	id INTEGER PRIMARY KEY,
	email TEXT NOT NULL,
	name TEXT NOT NULL,
        password TEXT NOT NULL,
	meal_start_day TEXT NOT NULL DEFAULT 'MONDAY',
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
