CREATE TABLE sessions (
	id INT NOT NULL AUTO_INCREMENT,
	session_id VARCHAR(255) NOT NULL,
	user_id INT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users(id)
)
